name: Linux

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  schedule:
    - cron: '0 10 * * *'

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Zig
        uses: mlugg/setup-zig@v2.0.5
        with:
          version: master
      - name: Install sdl2
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev
      - name: SDL version
        run: sdl2-config --version
      - name: Check format
        continue-on-error: true
        run: zig fmt --check .
      - name: Build and run tests
        run: zig build test
      - name: Build examples
        run: zig build -Dskip=particle_life,intersection_2d examples
