name: Windows (cross)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  schedule:
    - cron: '0 10 * * *'

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build-cross-windows:
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.host}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Zig
        uses: mlugg/setup-zig@v2.0.5
        with:
          version: master
      - name: Build examples
        run: zig build -Dtarget=x86_64-windows-gnu examples
