name: Native Build (windows)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-windows-gnu, x86_64-windows-msvc]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read .zig-version
        id: zigversion
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.zigversion
      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ steps.zigversion.outputs.content }}
      - name: Install VisualStudio (x64)
        if: ${{ matrix.target == 'x86_64-windows-msvc' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          uwp: false
          arch: x64
      - name: Download SDL2 (MinGW)
        uses: carlosperate/download-file-action@v1.0.3
        if: ${{ matrix.target == 'x86_64-windows-gnu' }}
        with:
          file-url: https://www.libsdl.org/release/SDL2-devel-2.30.9-mingw.tar.gz
          file-name: SDL2.tar.gz
          location: .
      - name: Download SDL2 (Visual Studio)
        uses: carlosperate/download-file-action@v1.0.3
        if: ${{ matrix.target == 'x86_64-windows-msvc' }}
        with:
          file-url: https://www.libsdl.org/release/SDL2-devel-2.30.9-VC.zip
          file-name: SDL2.tar.gz
          location: .
      - name: Extract SDL2
        uses: brunoborges/justextract@v1
        with:
          file: SDL2.tar.gz
      - name: Create SDK file
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: .build_config/sdl.json
          contents: |
            {
              "x86_64-windows-gnu": {
                "include": "SDL2-2.30.9/x86_64-w64-mingw32/include",
                "libs": "SDL2-2.30.9/x86_64-w64-mingw32/lib",
                "bin": "SDL2-2.30.9/x86_64-w64-mingw32/bin"
              },
              "x86_64-windows-msvc": {
                "include": "SDL2-2.30.9/include",
                "libs": "SDL2-2.30.9/lib/x64",
                "bin": "SDL2-2.30.9/lib/x64"
              }
            }
          write-mode: overwrite
      - name: Build and run tests
        run: zig build test
      - name: Build examples
        run: zig build -Dtarget=${{matrix.target}} examples

